version: '3'
services:
  chrome:
    image: selenium/standalone-chrome-debug:3.9.1-actinium
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      rails-network:
        aliases:
          - chrome.com
networks:
  rails-network: